import { Event } from "../types/event";

export const mockEvents: Event[] = [
  {
    id: "tm_1",
    source: "ticketmaster",
    sourceId: "1",
    title: "Concert Pop Live",
    description: "Un super concert en plein air",
    image: "https://picsum.photos/600/400",
    url: "https://example.com",
    date: "2026-03-12",
    time: "20:00",
    locationName: "Parc Central",
    address: "1 rue de la musique",
    city: "Paris",
    latitude: 48.8606,
    longitude: 2.3376,
    price: 25,
    category: "Music",
  },
  {
    id: "eb_2",
    source: "eventbrite",
    sourceId: "2",
    title: "Festival Food Truck",
    description: "Cuisine du monde entier",
    image: "https://picsum.photos/600/400",
    url: "https://example.com",
    date: "2026-03-15",
    time: "12:00",
    locationName: "Place de la République",
    address: "Place de la République",
    city: "Paris",
    latitude: 48.867,
    longitude: 2.363,
    price: null,
    category: "Food",
  },
];
